package lib.entities;

// Generated 04.01.2013 18:09:12 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", schema = "public")
public class User implements java.io.Serializable {
	private static final long serialVersionUID = -6077766902671048022L;
	
	private Integer id;
	private String username;
	private String password;
	private String token;
	private int coins;
	private Set<Request> requestsForSolverId = new HashSet<Request>(0);
	private Set<Peer> peers = new HashSet<Peer>(0);
	private Set<Request> requestsForSenderId = new HashSet<Request>(0);

	public User() {
	}

	public User(Integer id, String username, String password, String token,
			int coins) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.token = token;
		this.coins = coins;
	}

	public User(Integer id, String username, String password, String token,
			int coins, Set<Request> requestsForSolverId, Set<Peer> peers,
			Set<Request> requestsForSenderId) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.token = token;
		this.coins = coins;
		this.requestsForSolverId = requestsForSolverId;
		this.peers = peers;
		this.requestsForSenderId = requestsForSenderId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 16)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 40)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "token", nullable = false, length = 64)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "coins", nullable = false)
	public int getCoins() {
		return this.coins;
	}

	public void setCoins(int coins) {
		this.coins = coins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userBySolverId")
	public Set<Request> getRequestsForSolverId() {
		return this.requestsForSolverId;
	}

	public void setRequestsForSolverId(Set<Request> requestsForSolverId) {
		this.requestsForSolverId = requestsForSolverId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Peer> getPeers() {
		return this.peers;
	}

	public void setPeers(Set<Peer> peers) {
		this.peers = peers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userBySenderId")
	public Set<Request> getRequestsForSenderId() {
		return this.requestsForSenderId;
	}

	public void setRequestsForSenderId(Set<Request> requestsForSenderId) {
		this.requestsForSenderId = requestsForSenderId;
	}

}
